### ISSUE TITLE
Architecture decisions - initial thoughts

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#20]
I think we should take a moment to talk out the architecture of the hypercloud system. It's tempting to build a simple core server around leveldb and then sharded archives servers - and maybe that's the right call - but I dont think that will scale well, and I get *really nervous* about using custom software at scale without a very experienced devops team.

My analysis here involves some guesswork. I may get some things wrong.

We should have these questions in mind:

 - What is our scale target?
 - How will we scale horizontally?
 - How will we monitor nodes, and the network?
 - How will we handle failover and redundancy?
 - When can we use off-the-shelf solutions?

## Scale target

This determines almost every other decision.

If we don't use any off-the-shelf solutions (Postgres, Cassandra, Kafka, etc), I think we could handle 1k users with about 10k archives. If we expect that the archives will average ~5mb in size, that's 50GB of data.

But, 1k users is not that far off, and things get challenging pretty quickly. If we plan for it, and use some off-the-shelf software, I think we could reasonably target 10k-100k users / 100k-1mm archives (5TB of data), without having to significantly re-architect hypercloud.

The tradeoff is system complexity. A 1k target can probably be made into an easily-deployed bundle, whereas a 10-100k target requires some ops work. If we want hypercloud to be something that anybody can conveniently deploy ("your own hypercloud is easy!") then 1k is the right target. But, we'll have to rewrite a lot once we get to 1k.

As a quick reference, here's everything hypercloud will require, off the top of my head.

- Load balancer
- Caching server
- HTTP server
- User DB
- Archive DB
- Computed view DB
- Changes feed
- Indexer / Data-processing pipeline
- Monitoring

**Comment by pfrazee** [comment]
One other consideration: do we want to support search? EDIT: actually we can decide this later. We probably wouldnt want to use elasticsearch primarily.

**Comment by pfrazee** [comment]
It might also be smart to do v1 as an intentionally small-scale solution: One server process that does it all against the local FS and leveldbs.

**Comment by poga** [comment]
+1 on doing a v1 with the most familiar/simplest techs, and it will go a long way.

IMO most of the components mentioned here as "required" are ops-dependent(every Ops team have their favorite tool for these problems). 

If the core architecture is simple enough, scaling with different software/platform shouldn't be a hard problem. And there can be multiple ways to scale hypercloud based on personal preferences.

**Comment by pfrazee** [comment]
A small-scale v1 does let us focus on correctness first. But it won't scale without a rewrite.

Small v1 would store a lot of data on the local hd, via files and leveldb. We can add caching and move HTTP to other nodes, but the leveldb will have to go eventually; we'll want a better featured DB like Cassandra. We also can't move archive swarming to other nodes without considering how the indexing pipeline will work. So small v1 is really a single-node solution.

**Comment by max-mapper** [comment]
I think a single node solution can handle these parts for a long time without too much fuss:

- User accounts/authentication (township aka leveldb)
- Metadata storage/stats API (leveldb or sql)
- Web app serving (node http)

Reasoning here is that these parts don't involve much data/bandwidth, and are cacheable/optimizable.

Parts that should be on other nodes:

- Hypercore storage/serving (e.g. hypercore-archiver-server)
- Search (e.g. elasticsearch)
- Dat network crawlers (for statistics)

These will be the services that incur most of the processing/storage/bandwidth overhead. The crawlers will be a series of processes that query all dat keys on some interval and investigate swarms to collect stats like how many peers are online, how many copies of the data exist.

To avoid running an expensive (in time and money) elasticsearch thing up front we wanted to make sure we had great static html rendering on the webapp so you can nicely google for things. Since the web app will be more akin to NPM than GitHub (e.g. like npm, pages for dats aren't that dynamic and don't change too often, vs github which has many more interactive web app features) we can also cache a lot of the html views.

The idea of the architecture overall is to allow the hypercore storage nodes to live on other machines from the central metadata/state machine. So if we figure out that pattern it solves our horizontal scalability issue for the most part.

So I'd say a sensible v1 would be everything simple/single node except the hypercore archiving part, and we can skip search on v1. The crawlers ideally can run on any machine and just use the metadata api (if they have permission to) to update repo stats.

**Comment by pfrazee** [comment]
[Research document on component and platform options](https://gist.github.com/pfrazee/cd90586c827d3e806aef4b5c3b7929a7)

**Comment by pfrazee** [comment]
Consensus in IRC is in agreement with @poga. We're going to start with a single-node v1. That may include external caching components and HTTP frontends and etc, but we *should not* distribute our backend without reopening this issue and looking at reliable job queues, monitoring, and failover.

Closing for now.
