### ISSUE TITLE
Update to new Dat

### ISSUE THREAD

**Issue by pfrazee** [joehand/hypercloud#83]
Wait for hypercore/drive to stabilize then update to the new SLEEPy dat.

**Comment by joehand** [comment]
@pfrazee I think I fixed the progress bug you were having in dat-node 3.2.2. I didn't realize that the `opts.indexing` option got moved to hyperdrive, not the read stream. 

It was reimporting files because the mtime was getting updated after the initial import (that whole thing again). Once files got reimported, the historic content wasn't available, so it couldn't sync.

**Comment by pfrazee** [comment]
Good deal, will test soon

**Comment by pfrazee** [comment]
Things seem to be working!
